- hosts: all
  module_defaults:
    ansible.builtin.file:
      pip: pip3
      python: python3
  become: true
  tasks:
      - name: Update Repository Index
        apt:
          update_cache: Yes
        when: ansible_distribution in ("Ubuntu")

      - name: Install pip3, python3, Java open-jdk (Ubuntu)
        apt:
          name:
             - pip
             - python3
             - openjdk-8-jdk
          state: latest
        when: ansible_distribution == "Ubuntu"

      - name: Use pip3 as default pip
        shell: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

      - name: Use python3 as default python
        shell: update-alternatives --install /usr/bin/python python /usr/bin/python3 1

      - name: Install pip3, python3, Java open-jdk (CentOS)
        dnf:
          name:
             - python3-pip
             - python3
             - java-1.8.0-openjdk
          state: latest
        when: ansible_distribution == "CentOS"

      - name: Pytho3 as default
        ansible.builtin.command: alias python3=/usr/bin/python3
        when: ansible_distribution == "CentOS"

      - name: MOTD Deployer Defined
        copy:
           content: "Ansible Managed node by BencitoCutie"
           dest: /etc/motd

      - name: MOTD Default Deployer
        copy:
           content: "Ansible Managed node by BencitoCutie"
           dest: /etc/motd

      - name: Create user defined
        ansible.builtin.user:
           name: Bencito
           comment: Name
           uid: 1012
           group: root
           createhome: yes
           home: /home/Bencito
